### create diary
POST http://localhost:8080/create/diary?date=2022-07-03
Content-Type: application/json

{
  "text": "dkshk?"
}


### create diary2
POST http://localhost:8080/create/diary?date=2022-03-03
Content-Type: application/json

{
  "text": "공부하자?"
}


### read diary
GET http://localhost:8080/read/diary?date=2022-07-07
Content-Type: application/json


### read diaries
GET http://localhost:8080/read/diaries?startDate=2022-03-02&endDate=2022-07-08
Content-Type: application/json


### update diary
PUT http://localhost:8080/update/diary?date=2022-07-03
Content-Type: application/json

{
  "text": "this is new!~"
}


### delete diary
DELETE http://localhost:8080/delete/diary?date=2022-03-03
Content-Type: application/json
